### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ni-eminen** [JonathanHeyno/ot-harjoitustyo#1]
Koodi vaikuttaa OK. Paikoin esim. viittauksia taulukkoihin tehdään paljon, kuten esim. metodissa [__open_ended_n_in_direction](https://github.com/JonathanHeyno/ot-harjoitustyo/blob/636d79b5bedd84403df9e3b484e48108160ec942/src/entities/algorithms/valuebased.py#L69). Tällaisissa tilanteissa voisi luettavuutta kehittää tallentamalla coord[0] ja coord[1] joihinkin niiden arvojen merkitystä kuvaaviin muuttujiin. Myös kommentointia voisi lisätä, etenkin kun käytetään päällekkäisiä looppeja ym. mikä ei ole helposti ymmärrettävissä.

Ohjelma menee jumiin, mikäli ruutujen määräksi laittaa esimerkiksi 100. Tämä johtaa ainakin Ubuntulla kaikenlaisiin grafiikkabugeihin ja käyttökelvottomuuteen, ehkä ruutujen määrää voisi rajata?

Ohjelma näyttää noudattavan hyvin pylintin laatuvaatimuksia. Testejä on riittävästi (87 %) ja niiden tarkoitus on helppo ymmärtää. Koodi on siivoa muutenkin ja kansiorakenne oikein kaunista katseltavaa.

Aika: 2.5.2022 20:05

**Comment by JonathanHeyno** [comment]
Enpä itse huomannut tota että ohjelma jumittaa kun laittaa liikaa ruutuja, hyvä kun huomasit. Nyt rajoitetu max 50x50 ruudukkoon. Kommentointia myös lisätty koodiin.
